### PR TITLE
Add kestrel logging

### PR DESCRIPTION
**Pull request by wsargent**
Add logging with a block, i.e.

```
def addOne(input:Int): Int = logger.debug {
  input + 1
}
```

### CODE REVIEW

**Comment by analytically** [comment]
@wsargent is this still relevant?

**Comment by wsargent** [comment]
@analytically I'm not sure what you mean.  It merges.  Are you asking if it's useful?

**Comment by analytically** [comment]
Yeah, and if you still want it merged. If so, can you implement @hseeberger's requested changes? Thanks!

**Comment by tylerjharden** [comment]
@analytically It is useful if you want to follow functional/reactive paradigms. Some examples in MEAP's Functional & Reactive Domain Modeling, as well as MEAP's Functional Programming in Scala, the use of a logger using a Kestrel monad to execute the side-effect is rather clean.

If @wsargent has abandoned/no longer wishes to update, I wouldn't mind making the necessary changes to get this PR merged in, as I would like to use this library, but only if I can use Kestrel as that is how I currently do logging with a own custom logging wrapper we use for a client project.

**Comment by wsargent** [comment]
@tylerjharden go right ahead, I have my hands full right now.

**Pull request closed without merging**
