### PR TITLE
osgified

### PR DESCRIPTION
**Pull request by FeiWongReed**
Small build changes to introduce osgi support

### CODE REVIEW

**Comment by analytically** [comment]
Can you remove the commented out line, and rename to 'Add OSGi bundle via sbt-osgi.'. Thanks!

**Comment by FeiWongReed** [comment]
Done. So, could you merge this and make a release?

**Comment by FeiWongReed** [comment]
Thank you, but what about a [small] release? ^_^

**Comment by analytically** [comment]
Yeah I'm working on it. Don't have publish rights yet. :-)

**Comment by FeiWongReed** [comment]
So, thank you again

**Pull request merged**
